#!/bin/sh
#Exit with Not 0 will abort the commit

current_branch=$(git rev-parse --abbrev-ref HEAD)

echo $current_branch;

if [ $current_branch = "master" ]; then

echo  "You are on the master branch.
You can't commit directly on the master branch.
Please check your git workflow for more details";
exit 1; #OK

else

	exit 0; #OK

fi

exit 1 #KO
